DROP TABLE IF EXISTS questions CASCADE;

CREATE TABLE questions (
  id SERIAL NOT NULL,
  quiz_id INTEGER REFERENCES quizzes(id) NOT NULL ON DELETE CASCADE,
  body VARCHAR(255) NOT NULL,
  difficulty SMALLINT NOT NULL
);