DROP TABLE IF EXISTS question_ratings CASCADE;

CREATE TABLE question_ratings (
  id SERIAL NOT NULL,
  user_id INTEGER REFERENCES users(id) NOT NULL ON DELETE CASCADE,
  question_id INTEGER REFERENCES questions(id) NOT NULL ON DELETE CASCADE,
  rating SMALLINT NOT NULL,
  comment VARCHAR(255)
);