DROP TABLE IF EXISTS quiz_sessions CASCADE;

CREATE TABLE quiz_sessions (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
  start_time TIMESTAMP DEFAULT NOW(),
  end_time TIMESTAMP
);